services:
  livebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Elixir Version: 1.9, 1.10, 1.10.4, ...
        VARIANT: "1.17.3-erlang-27.2-ubuntu-focal-20241011"
        # Livebook Version
        LIVEBOOK_VERSION: "v0.14.5"
    environment:
      - MIX_ENV=prod
      - ELIXIR_ERL_OPTIONS=-epmd_module Elixir.Livebook.EPMD
    ports: 
      - "8080:8080"
      - "8081:8081"
    command: sleep infinity
